### ISSUE TITLE
Upgrade to Drupal 10

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/recap#244]
- [x] Audit contributed modules active in site for compatibility with Drupal 10
- [x] Upgrade any that are to versions that are compatible with both Drupal 9 and 10
- [x] Add contrib project for admin theme seven (we had to do for researchdata https://github.com/pulibrary/researchdata/pull/258)
- [x] Any that are not compatible considering removing, otherwise create a new issue to deal with a blocker to the upgrade. 
- [x] Upgrade the .lando.yml file to use the drupal10 recipe. 
- [ ] Upgrade to Drupal 10. If it complains about deprecated modules, work on the tickets to remove those. If it doesn't complain, close the tickets.
   - [x] https://github.com/pulibrary/recap/issues/252 
   - [x] https://github.com/pulibrary/recap/issues/253
   - [x] https://github.com/pulibrary/recap/issues/254
- [x] Test on staging
- [x] Deploy to prod

This step-by-step guide was helpful to successfully upgrade the researchdata site: https://www.drupal.org/docs/upgrading-drupal/upgrading-from-drupal-8-or-later/upgrading-a-composer-based-site
See: https://www.drupal.org/docs/upgrading-drupal/upgrading-from-drupal-8-or-later/upgrading-from-drupal-9-to-drupal-10/overview

**Comment by maxkadel** [comment]
Successfully deployed to staging! Still needs to be deployed to production.

**Comment by kevinreiss** [comment]
Deployed to prod. Closing
